FROM chgeuerregistry1.azurecr.io/chgeuer/elixir:1.4.4

ENV HOME=/opt/app/ TERM=xterm

WORKDIR /opt/app

ENV MIX_ENV=prod REPLACE_OS_VARS=true

# Cache elixir deps
COPY src3/mix.exs mix.lock ./
COPY src3/config ./config
COPY src3 .

RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get && \
    mix deps.compile && \
    mix release --env=prod
