######################################
#
# Ingress
#
######################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-app
  annotations:
    nginx.com/sticky-cookie-services: "serviceName=app srv_id expires=10m path=/app"
spec:
  backend: 
    serviceName: app
    servicePort: 80
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /app
        backend:
          serviceName: app
          servicePort: 80
---
######################################
#
# Service
#
######################################
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: LoadBalancer
  sessionAffinity: None
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: app
---
######################################
#
# ReplicationController
#
######################################
apiVersion: v1
kind: ReplicationController
metadata: 
  name: app
  labels: 
    zone: prod
    version: 1.0.0
spec:
  replicas: 4
  selector: 
    app: app
  template:
    metadata:
      labels: 
        app: app
    spec:
      containers:
      - name: app
        image: chgeuerregistry2.azurecr.io/chgeuer/app:1.0.0
        imagePullPolicy: Always
        ports: 
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: SECRET_KEY_BASE
          value: highlysecretkey
        - name: MIX_ENV
          value: prod
      imagePullSecrets:
      - name: chgeuerregistry2
