apiVersion: v1
kind: Pod
metadata: 
  name: app
  labels: 
    zone: prod
    version: 1.0.0
spec:
  containers:
  - name: app
    image: chgeuerregistry1.azurecr.io/chgeuer/app:1.0.0
    imagePullPolicy: Always
    env:
    - SECRET_KEY_BASE: highlysecretkey
    - MIX_ENV: prod
    - PORT: 8000
    ports: 
    - containerPort: 8000
  imagePullSecrets:
  - name: chgeuerregistry1
