apiVersion: v1
kind: Pod
metadata: 
  name: app
  labels: 
    zone: prod
    version: 1.0.0
spec:
  containers:
  - name: app
    image: 97c0c098ae10
    imagePullPolicy: Always
    ports: 
    - containerPort: 8080
  imagePullSecrets:
  - name: chgeuerregistry1
