######################################
#
# Service
#
######################################
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    name: http
  selector:
    app: app
---
######################################
#
# ReplicationController
#
######################################
apiVersion: v1
kind: ReplicationController
metadata: 
  name: app-rc
  labels: 
    zone: prod
    version: 1.0.0
spec:
  replicas: 20
  selector: 
    app: app
  template:
    metadata:
      labels: 
        app: app
    spec:
      containers:
      - name: app
        image: chgeuerregistry1.azurecr.io/chgeuer/app:1.0.0
        imagePullPolicy: Always
        ports: 
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: SECRET_KEY_BASE
          value: highlysecretkey
        - name: MIX_ENV
          value: prod
      imagePullSecrets:
      - name: chgeuerregistry1
