apiVersion: batch/v1 
kind: Job 
metadata:
  # generateName: build-job-
  name: build-job-${uuid}
spec: 
    template: 
        metadata:
            name: build-job-${uuid}
            annotations:
                pod.beta.kubernetes.io/init-containers: '[
                    {
                        "name": "download-git-repo",
                        "image": "chgeuer/chgeuer-docker-utils",
                        "imagePullPolicy": "IfNotPresent",
                        "command": [ "git", "clone", "https://github.com/chgeuer/k8s_elixir.git", "/git" ],
                        "volumeMounts": [
                            {
                                "mountPath": "/git",
                                "name": "git"
                            }
                        ]
                    }
                ]'
        spec:
            restartPolicy: Never
            volumes: 
              - name: docker-graph-storage 
                emptyDir: {}
              - name: git
                emptyDir: {}
            containers: 
              - name: build-job
                image: docker:stable-dind
                securityContext: 
                    privileged: true 
                resources: 
                    requests: 
                        cpu: 20m 
                        memory: 512Mi 
                volumeMounts: 
                  - name: docker-graph-storage 
                    mountPath: /var/lib/docker 
                  - name: git 
                    mountPath: /git
                env: 
                  - name: DOCKER_HOST 
                    value: tcp://localhost:2375 
                  - name: DOCKER_SECRET_CFG
                    valueFrom:
                      secretKeyRef:
                        name: chgeuerregistry1.azurecr.io
                        key:  .dockercfg
                command: [ '/bin/sh', '/git/dind/create-docker-image.sh']
