apiVersion: batch/v1 
kind: Job 
metadata: 
    name: dind 
spec: 
    template: 
        metadata:
            name: dind
            annotations:
                pod.beta.kubernetes.io/init-containers: '[
                    {
                        "name": "download-git-repo",
                        "image": "chgeuer/chgeuer-docker-utils",
                        "imagePullPolicy": "IfNotPresent",
                        "command": [ "git", "clone", "https://github.com/chgeuer/k8s_elixir.git", "/gitsource" ],
                        "volumeMounts": [
                            {
                                "mountPath": "/gitsource",
                                "name": "gitsource"
                            }
                        ]
                    }
                ]'
        spec:
            restartPolicy: Never
            volumes: 
              - name: docker-graph-storage 
                emptyDir: {}
              - name: gitsource
                emptyDir: {}
            containers: 
              - name: dind-daemon 
                image: docker:1.12.6-dind 
                resources: 
                    requests: 
                        cpu: 20m 
                        memory: 512Mi 
                securityContext: 
                    privileged: true 
                volumeMounts: 
                  - name: docker-graph-storage 
                    mountPath: /var/lib/docker 
              - name: docker-cmds 
                image: docker:1.12.6
                resources: 
                    requests: 
                        cpu: 10m 
                        memory: 256Mi 
                env: 
                  - name: DOCKER_HOST 
                    value: tcp://localhost:2375 
                  - name: DOCKER_SECRET_CFG
                    valueFrom:
                      secretKeyRef:
                        name: chgeuerregistry1.azurecr.io
                        key:  .dockercfg
                volumeMounts: 
                  - name: gitsource 
                    mountPath: /gitsource
                command: [ '/bin/sh', '/gitsource/dind/create-docker-image.sh']
