FROM alpine:3.6

RUN echo 'http://dl-4.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories && \
    apk --update add ncurses-libs

ENV MIX_ENV=prod \
    REPLACE_OS_VARS=true \
    PORT=8000 \
    HOST=example.com \
    SECRET_KEY_BASE=highlysecretkey

WORKDIR /

COPY ./k8s_elixir.tgz /k8s_elixir.tgz

RUN tar xvfz k8s_elixir.tgz -C / && \
    rm /k8s_elixir.tgz

EXPOSE $PORT

ENTRYPOINT ["/opt/app/_build/prod/rel/k8s_elixir/bin/k8s_elixir", "foreground"]
